version: '3.5'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    container_name: postgres
    ports:
      - '5432:5432'
    networks:
      - job-app

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-docker-postgres
    ports:
      - '5000:5000'
    depends_on:
      - db
    volumes:
      - ./src:/app/src
    networks:
      - job-app

  pgadmin:
    image: dpage/pgadmin4
    container_name: nest-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    depends_on:
      - db
    networks:
      - job-app

networks:
  job-app:
    name: job-app
    external: true